---
language: node_js
node_js:
  - "4"

sudo: required

services:
  - docker

cache:
  directories:
    - node_modules

before_install:
  - npm config set spin false
  - npm install -g bower
  - bower --version
  - npm install phantomjs-prebuilt
  - phantomjs --version

install:
  - npm install
  - bower install

script:
  - npm test

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    VERSION=`node -e "console.log(require('./package.json').version);"`;
    docker build -t foursball/foosball .;
    if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker tag foursball/foosball foursball/foosball:$VERSION;
      docker push foursball/foosball:latest;
      docker push foursball/foosball:$VERSION;
    elif [ "$TRAVIS_BRANCH" == "dev" ]; then
      docker tag foursball/foosball foursball/foosball:latest-dev;
      docker push foursball/foosball:latest-dev;
    else
      docker tag foursball/foosball foursball/foosball:$TRAVIS_BRANCH;
      docker push foursball/foosball:$TRAVIS_BRANCH;
    fi
